sidebar_title: "项志鹏的博客"
sidebar_subtitle: "山高自有可行路<br>水深自有渡船人。"

truncate_len: 60

archives: true

# Choose the comment service according to your need.
# Please do not use the two services at the same time.
livere: # [data-uid] for livere.com
disqus: zhipengxiang for disqus.com