sidebar:
  articles: Articles
  tags: Tags
  categories: Categories
  toggle_site: 去主页
  toggle_article: 去看所有文章
  catalog: 目录
  have_read: 已经阅读了

footer:
  driven: Driven
  theme: Theme

copy:
  success: 复制成功
  error: 复制错误
  noSupport: The browser does not support

page:
  articles: 所有文章
  tag: 文章标签
  category: 文章分类
  archives: 文章归档

sticky: Sticky
no_title: No title
read_more: Read more

post:
  created: created
  updated: updated
  wordcount: '总字数'
  min2read: '阅读全文需要: %s min'
  copyright:
    author: 作者
    link: 分享链接
    copyright_notice: 版权申明
    copyright_content: '可转载、引用，但需经本人同意后署名作者且注明文章出处，并以相同方式共享。'


search: Search
algolia_search:
  input_placeholder: Search for Posts
  hits_empty: "We didn't find any results for the search: ${query}."
  hits_stats: "${hits} results found in ${time} ms"

local_search:
  label: 搜索文章
  input_placeholder: 从文章中搜索...
  hits_empty: "抱歉，没有找到您想要的结果: ${query}"
  powered_by: Powered by
